### ISSUE TITLE
Add Slack notification for E2E test failures

### ISSUE THREAD

**Issue by MH4GF** [liam-hq/liam#859]
## Overview
Add Slack notification functionality when E2E tests fail.

## Background & Purpose
- To detect E2E test failures early and enable quick response
- To maintain consistency with other workflows that already have similar notification features

## Implementation Details
1. Add a Slack notification step for failures in `.github/workflows/_run_e2e_test.yml`
2. Following the existing implementation (in released_package_test.yml), notify:
   - Test name
   - Failed browser
   - Result (failure)

## Implementation Example
```yaml
- name: Slack Notification on Failure
  if: failure()
  uses: tokorom/action-slack-incoming-webhook@d57bf1eb618f3dae9509afefa70d5774ad3d42bf
  env:
    INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_CLI_CI_WEBHOOK_URL }}
  with:
    text: "E2E Test Failure"
    attachments: |
      [
        {
          "color": "bad",
          "fields": [
            {
              "title": "Browser",
              "value": "${{ matrix.browser }}"
            },
            {
              "title": "Result",
              "value": "failure"
            }
          ]
        }
      ]
```

## Notes
- Notifications will be sent only on test failures
- Will use the existing Slack Webhook URL
- Implementation follows the pattern used in released_package_test.yml
